[project]
name = "yahoo"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "currencyconverter>=0.18.10",
    "pandas>=3.0.5",
    "pandas-stubs~=3.0.5",
    "requests>=2.34.2",
    "st-copy>=2.0.0",
    "streamlit>=1.64.0",
    "streamlit-searchbox>=0.1.24",
    "yfinance>=1.7.0",
    "st-copy>=0.1.0",
]
